---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "SqlPad - A web app for running SQL queries and visualizing the results"
keywords:    "SqlPad, node.js, Postgres, postgresql, mysql, microsoft sql server, online sql editor"
description: "SqlPad is a web app for writing and running SQL queries and visualizing the results. Supports Postgres, MySQL, and SQL Server. Built with Node.js"
source_link: "https://github.com/rickbergfalk/sqlpad"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: "UA-54318769-1"


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  
