version: '3'
services:
  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - 6379:6379

  ldap:
    image: rroemhild/test-openldap
    restart: always
    ports:
      - 10389:10389
    healthcheck:
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 20s

  mssql:
    image: 'mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-16.04'
    hostname: 'mssql'
    restart: always
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuperP4ssw0rd!
      - MSSQL_PID=Express
    healthcheck:
      test:
        [
          'CMD',
          '/opt/mssql-tools/bin/sqlcmd',
          '-S',
          'localhost',
          '-U',
          'sa',
          '-P',
          'SuperP4ssw0rd!',
          '-Q',
          'SELECT 1',
        ]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 20s

  postgres:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_USER: sqlpad
      POSTGRES_PASSWORD: sqlpad
      POSTGRES_DB: sqlpad
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 20s

  mariadb:
    image: mariadb:10.3
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ['CMD', 'mysqladmin', 'status', '-uroot', '-ppassword']
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 20s

  mysql:
    image: mysql:8
    restart: always
    ports:
      - 23306:3306
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db2
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ['CMD', 'mysql', '-uuser', '-ppassword', '-e', 'select 1']
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 20s
